name: Hashi CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']

jobs:
  test-sass:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ '18.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Use NodeJS version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn test:sass
